name: Build PWA to APK

on:
  push:
    branches:
      - main # 或者您的主分支名称
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 您可以根据需要调整 Node.js 版本

      - name: Install bubblewrap-cli
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: bubblewrap build --manifest twa-manifest.json --skip-web-manifest-update
        
      - name: List files
        run: ls -la

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pwa-apk
          path: app-release-unsigned.apk # bubblewrap 默认输出的文件名